version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_container
    command: >
      sh -c " python manage.py migrate &&
      python manage.py loaddata fake_db &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    container_name: python_mysql
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_challenge
      MYSQL_USER: challenge
      MYSQL_PASSWORD: challenge1234
    ports:
      - "3307:3306"
    volumes:
      - ./datadb:/var/lib/mysql
